language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
script:
  - coverage run -m pytest


addons:
  coveralls:
    repo_token:fE0XpQH3HSMo8ydug9rlqtzC80ZAhuR9t

after_success:
  - coveralls

branches:
  - /.*/